#!/usr/bin/env bash


# Herbstluft config file
# 
# Created by Nightlamp
# TODO: add audio buttons etc
# TODO: migrate to sxhkd for keybindings
#-------------------------#

# shorten herbstclient to hc
hc() {
    herbstclient "$@"
}

# reloads all currently running herbstclients
hc emit_hook reload

# unbind everything
hc keyunbind --all


#---------------#
## Desktop setup
bgim='/home/no5a/Pictures/backgrounds/tripleCircle/bigImage1366.png'

# Desktop image
feh --bg-scale "$bgim"

# Lock Screen
hc keybind $Mod-Delete spawn i3lock


### Keybindings
# Win key as mod
Mod=Mod4

## WM Control Settings
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-Escape quit

## Program launching
hc keybind $Mod-t spawn ${TERMINAL:-xfce4-terminal}
hc keybind $Mod-space spawn dmenu_run_hlwm


## Frame Control
# Make Frames
hc keybind $Mod-Control-h split left    0.5
hc keybind $Mod-Control-j split bottom  0.5
hc keybind $Mod-Control-k split top     0.5
hc keybind $Mod-Control-l split right   0.5

# Remove Frames
hc keybind $Mod-Shift-q remove

# Resize frames
rstep=0.02

hc keybind $Mod-Left  resize left  +$rstep
hc keybind $Mod-Down  resize down  +$rstep
hc keybind $Mod-Up    resize up    +$rstep
hc keybind $Mod-Right resize right +$rstep


## Client Control
# client focussing
hc keybind $Mod-h focus left
hc keybind $Mod-j focus down
hc keybind $Mod-k focus up
hc keybind $Mod-l focus right

# client cycling in frame
hc keybind $Mod-n cycle
hc keybind $Mod-b cycle -1

# Fullscreen
hc keybind $Mod-m fullscreen toggle

# close client
hc keybind $Mod-q close


## Mouse Control
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 resize


# Try max layout as default frame layout
hc set default_frame_layout 2
herbstclient load ${TAG_NAMES[0]} '(clients max:0)'


## Tags
tagNames=( {1..9} 0 )
tagKeys=( {1..9} 0 )

# set tags to tagNames and keys to tagKeys
hc rename default "${tagNames[0]}" || true
for i in ${!tagNames[@]} ; do
    hc add "${tagNames[$i]}"
    key="${tagKeys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done


## Layouts
hc keybind $Mod-f floating toggle

### Theme
# reset themes for tiling and floating windows
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1

focusColor='#e47200'  # yellowish
normalColor='#4e0027' # dark red
# Frame Theming
hc set frame_border_active_color $focusColor
hc set frame_border_normal_color '#1b1b1b' 
hc set frame_bg_normal_color     $normalColor
hc set frame_bg_active_color     $focusColor
hc set frame_border_width 1
hc set always_show_frame 1
hc set frame_bg_transparent 1
hc set frame_transparent_width 3
hc set frame_gap 4

## non-frame theming
hc attr theme.active.color $focusColor
hc attr theme.normal.color $normalColor
hc attr theme.urgent.color '#005d5d'
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 3
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#3E4A00'
hc attr theme.active.outer_color '#3E4A00'
hc attr theme.background_color '#141414'
hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0


### Rules
# copy from default autostart file
# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
hc detect_monitors

# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" $monitor &
done
