#!/usr/bin/env bash


# Herbstluft config file
# 
# Created by Nightlamp
# TODO: migrate to sxhkd for keybindings
# TODO: set a extra "monitor", overlay with all current monitors and use it for 
#				floating


##----------------------------------------------------------------------------##
## Global Vars

bgim='/home/no5a/Pictures/backgrounds/tripleCircle/bigImage.png'
hcHome="${HOME}/.config/herbstluftwm"

tagNames=( {1..9} 0 )
tagKeys=( {1..9} 0 )

Mod=Mod4

##----------------------------------------------------------------------------##
## Herbstluft init
# shorten herbstclient to hc
hc() {
    herbstclient "$@"
}

## Reset hc
# reloads all currently running herbstclients
hc emit_hook reload
# unbind everything
hc keyunbind --all
# set how trees are displayed
hc set tree_style '╾│ ├└╼─┐'

# Locks screen while things are updated/initted
hc lock

##----------------------------------------------------------------------------##
## Rules
${hcHome}/modules/rules.sh


swap_monitors_to_get_tag=0

##----------------------------------------------------------------------------##
## Theme
${hcHome}/modules/theme.sh 


##----------------------------------------------------------------------------##
## Keybinds
${hcHome}/modules/keybinds.sh "$Mod"


##----------------------------------------------------------------------------##
## WM behaviour

hc set focus_follows_mouse 1

# Try max layout as default frame layout
hc set default_frame_layout 2
herbstclient load ${TAG_NAMES[0]} '(clients max:0)'


##----------------------------------------------------------------------------##
## Tags

# set tags to tagNames and keys to tagKeys
hc rename default "${tagNames[0]}" || true
for i in ${!tagNames[@]} ; do
    hc add "${tagNames[$i]}"
    key="${tagKeys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "${Mod}-${key}" use_index "$i"
        hc keybind "${Mod}-Shift-${key}" move_index "$i"
    fi
done


##----------------------------------------------------------------------------##
## Desktop setup

# bar setup
killall lemonbar
hc pad 0 15 0 0
${hcHome}/barFeeder.sh | lemonbar -p &
# Desktop image
feh --bg-scale "$bgim"
# Lock Screen
hc keybind $Mod-Delete spawn ${hcHome}/modules/lock.sh "$bgim"

# the panel (OLD)
oldPanel() {
	panel=~/.config/herbstluftwm/panel.sh
	[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
	for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
			# start it on each monitor
			"$panel" $monitor &
	done
}
#oldPanel

##----------------------------------------------------------------------------##
##misc

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
hc detect_monitors

# unlocks changes, stops ragged startup
hc unlock



